<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>


<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">

      <h1>Обновление данных пользователя</h1>

      <form action="/users/<?= $user["id"] ?>" method="post">
        <input type="hidden" name="_METHOD" value="PATCH">
        
        <div class="form-group">
          <label for="name">Имя</label>
          <input type="text" class="form-control" name="user[name]" value="<?= $user['name'] ?>">
          <?php if (isset($errors['name'])) : ?>
            <font color="red"><?= $errors['name'] ?></font>
          <?php endif ?>
        </div>

        <div class="form-group">
          <label>Email</label>
          <input type="text" class="form-control" name="user[email]" value="<?= $user['name'] ?>" placeholder="name@gmail.com">
          <?php if (isset($errors['email'])) : ?>
            <font color="red"><?= $errors['email'] ?></font>
          <?php endif ?>
        </div>


        <div class="form-group">
          <label>Password</label>
          <input type="password" name="user[password]" class="form-control" value="<?= $user['password'] ?>" placeholder="Must be 8-20 characters long.">
          <?php if (isset($errors['password'])) : ?>
            <font color="red"><?= $errors['password'] ?></font>
          <?php endif ?>
        </div>
        
        <br><button type="submit" class="btn btn-primary">Обновить</button>
      </form>

      <form action="/users">
        <input type="submit" class="btn btn-outline-success" value="Все пользователи">
      </form>
    </div>
  </div>
</div>