<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<div class="container">
    <div class="row">
        <div class="col-md-9 offset-md-2">
            
            <?php if (count($flash) > 0) : ?>
                <ul>
                    <?php foreach ($flash as $messages) : ?>
                        <?php foreach ($messages as $message) : ?>
                            <li><?= $message ?></li>
                        <?php endforeach ?>
                    <?php endforeach ?>
                </ul>
            <?php endif ?>

            <h1>Пользователи</h1>
            <form action="/users">
                <div class="input-group">
                    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                    <input class="btn btn-primary btn-sm" type="submit" value="Поиск">
                </div>
            </form>

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Имя</th>
                        <th scope="col">@Email</th>
                    </tr>
                </thead>
                <tbody>
  
                    <?php foreach ($users as $user) : ?>
                        <tr>
                            <td><?= htmlspecialchars($user['name']) ?></td>
                            <td><?= htmlspecialchars($user['email']) ?></td>
                            <td class="table-light">
                                <form action="users/<?= htmlspecialchars($user['id']) ?>">
                                    <input class="btn btn-primary btn-sm" style="height:30px;width:70px" type="submit" value="user">
                                </form>
                            </td>
                            <td class="table-light">
                                <form action="/users/<?= htmlspecialchars($user['id']) ?>/edit">
                                    <input class="btn btn-primary btn-sm" style="height:30px;width:70px" type="submit" value="update">
                                </form>
                            </td>

                            <td class="table-light">
                                <form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
                                    <input type="hidden" name="_METHOD" value="DELETE">
                                    <input class="btn btn-primary btn-sm" style="height:30px;width:70px" type="submit" value="delete">
                                </form>
                            </td>
                        </tr>
                    <?php endforeach ?>

                </tbody>
            </table>

            <form action="/users/create">
                <br><button class="btn btn-outline-success">Добавить пользователя</button>
            </form>
        </div>
    </div>
</div>